language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: gj92njKqU6DEOMmiXkv3lGqn3sf2jVMvZdsily8mxCPVE/aG4aqbIFCFansWHmftKlncbCfV6sw2iGOEIe5qPaPkrvdv3ZMsh2J1yiAV1THzDXDH/NicwQg6N9F+MjQXBcdfSqxAsmoytBjmN6BHhaX4n9+iwPpAZLorSpBO6HON9EcXZBTLprOz0dKoOiP67yxdpX8eg/nb9JKUbv8j91wr0sd5G8PVP3oEwyKwN/THVGiY1eTlKl5Fr1cxiMj7TVuqtxxviXaL1z8fmUfRkMM54fURM9lqTskTdnYW2KOL1qxqsLdwjIr1114ElBTfrAlOvc44wKCYyd9YxpZnhP1XIZnK5v6HsnEMdVd5vGIskbYDPTixS1/MUQoyiOqpWgr9iSkfU1zHKacAndBrr48xi9a5QE/4S1BQ81VM07eWXblPX7zE5RbxbuBY0y/udX73jObNPFJ9pXV8eBVTh8FYVknQ45pQfIvPz65N/XGZGPSU3MUBv4n7llOhk2f00jtBJT3Ywpz2zhE3xZm9OpBs9DiKTGn9JU7OKGrFwIGjx0BtXqG3TsSD5IoGhmoaa6nW3M3Opz2qXYmYS4ksoRE0Gosl8zibejUcHh8r9snoPMPcfmduOMqmk1vMdHa5MYtj9JxdrxFMrSABsuLgSnoh4BU6To8a7WGamDJ2P50=
  app: damico-recipes-api
  on:
    repo: miamiyankee13/damico-recipes-api
